### ISSUE TITLE
X86/ ALSA: test UCM2, remove manually added rt5672 codec

### ISSUE THREAD

**Issue by gkkpch** [volumio/volumio-os#2]
Debian Buster only supported UCM and was incomplete, therefore the x86 recipe manually added the rt5672 codec.
Debian Bookworm fully supports UCM2 with all currently known codecs, the added rt5672 codec is now old and obsolete.

**Comment by foonerd** [comment]
@gkkpch - Do we know enough to deal with this issue?

**Comment by gkkpch** [comment]
It has already been taken care off, the x86 i,age already runs with ucm2 with no issues at all (e.g. dell 3040 audio issues resolved).
